name: XTC Build and Tests

# Runs on pushes targeting the main branch, pull request and manual Actions tab
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-15]
        python-version: ["3.12"]
    steps:
      - name: Checkout XTC Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Ensure PR has linear history
        if: github.event_name == 'pull_request'
        run: |
          MERGE_COMMITS="$(git rev-list --merges "$GITHUB_SHA^1..$GITHUB_SHA^2")"
          if [ -n "$MERGE_COMMITS" ]; then
            echo "::error::PR contains merges, always use rebase for updating branches: Merge commits: $MERGE_COMMITS" >&2
            exit 1
          fi
      - name: Install Distro Packages
        if: runner.os == 'Linux'
        # Note: package cache with awalsh128/cache-apt-pkgs-action does not work correctly, use standard install.
        run: |
          sudo apt install -y build-essential libomp5 binutils-aarch64-linux-gnu binutils-x86-64-linux-gnu libpfm4-dev
      - name: Install macOS Brew Packages
        if: runner.os == 'macOs'
        run: |
          brew install libomp
          export DYLD_LIBRARY_PATH="/opt/homebrew/opt/libomp/lib:$DYLD_LIBRARY_PATH"
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
      - name: Display Python version
        run: |
          python -c "import sys; print(sys.version)"
          pip list
      - name: Install XTC Package in dev mode
        run: |
          pip install -e .[dev]
      - name: Install TVM dependencies
        if: runner.os == 'Linux'
        run: |
          pip install -r tvm_requirements.txt
      - name: Install MLIR dependencies
        if: runner.os == 'Linux'
        run: |
          pip install -r mlir_requirements.txt
      - name: Install macOS TVM dependencies
        if: runner.os == 'macOS'
        run: |
          pip install -r macos_tvm_requirements.txt
      - name: Install macOS MLIR dependencies
        if: runner.os == 'macOS'
        run: |
          pip install -r macos_mlir_requirements.txt
      - name: List Python Packages
        run: |
          pip list
      - name: Run Checks
        if: runner.os == 'Linux'
        run: |
          make check
      - name: Run Basic macOS Tests
        # make check if not passing as of now
        if: runner.os == 'macOS'
        run: |
          make test
